#!/usr/bin/env bash
set -euo pipefail
note_binary=$1
note_temp=$(mktemp -d)
trap 'rm -rf "$note_temp"' EXIT
mkdir -p "$note_temp/root/cheminformatics"
"$note_binary" --config "$note_temp/config.toml" init --root "$note_temp/root"
"$note_binary" completion bash > "$note_temp/note.bash"
"$note_binary" completion zsh > "$note_temp/note.zsh"
"$note_binary" completion fish > "$note_temp/note.fish"
export NOTE_SMOKE_BINARY="$note_binary" NOTE_SMOKE_CONFIG="$note_temp/config.toml" NOTE_SMOKE_TEMP="$note_temp"
# Run generated scripts and their real callback in the appropriate shell.
bash --noprofile --norc <<'BASH'
set -e
note() { "$NOTE_SMOKE_BINARY" "$@"; }
source "$NOTE_SMOKE_TEMP/note.bash"
_init_completion() { cur="${COMP_WORDS[COMP_CWORD]}"; prev="${COMP_WORDS[COMP_CWORD-1]}"; words=("${COMP_WORDS[@]}"); cword=$COMP_CWORD; }
compopt() { :; } # UI sink requires Readline's active completion context.
COMP_WORDS=(note --config "$NOTE_SMOKE_CONFIG" new chemin)
COMP_CWORD=4
set +e
__start_note
set -e
test "${COMPREPLY[0]}" = 'cheminformatics/'
BASH
# Zsh's compadd requires an active ZLE completion context, so stub only the
# final UI sink and assert the candidate generated by the loaded callback.
# macOS ships Zsh with its required completion/regex modules; the conda-forge
# macOS package omits those modules. Linux uses the locked Pixi Zsh package.
case "$(uname -s)" in Darwin) note_zsh=/bin/zsh ;; *) note_zsh=zsh ;; esac
"$note_zsh" -f <<'ZSH'
set -e
autoload -Uz compinit
compinit -D
note() { "$NOTE_SMOKE_BINARY" "$@"; }
source "$NOTE_SMOKE_TEMP/note.zsh"
_arguments() { :; }
_describe() { print -rl -- "${completions[@]}"; }
compadd() { print -rl -- "$@"; }
words=(note --config "$NOTE_SMOKE_CONFIG" new chemin)
CURRENT=5
result=$(_note || :)
[[ "$result" == *'cheminformatics/'* ]]
ZSH
fish --no-config <<'FISH'
function note
  $NOTE_SMOKE_BINARY $argv
end
source "$NOTE_SMOKE_TEMP/note.fish"
set candidates (complete -C "note --config $NOTE_SMOKE_CONFIG new chemin")
string match -q '*cheminformatics/*' -- $candidates
or exit 1
FISH
printf 'Bash, Zsh, and Fish completion callbacks passed.\n'
